/*
 * RSAbstractByteBuffer.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: gj => java.lang.Object
public class RSAbstractByteBuffer extends RSClassWrapper {

    public RSAbstractByteBuffer(Object ref) {
        super(ref);
    }

    public static boolean getDirectBufferUnavailable() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("AbstractByteBuffer", "directBufferUnavailable", null);
    }

}
