/*
 * RSAbstractSoundSystem.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: dd => java.lang.Object
public class RSAbstractSoundSystem extends RSClassWrapper {

    public RSAbstractSoundSystem(Object ref) {
        super(ref);
    }

    public static RSClanMember[] getClanMembers() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("AbstractSoundSystem", "clanMembers", null);
        RSClanMember[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSClanMember[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSClanMember)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public static Object[] getRSRef_ClanMembers() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("AbstractSoundSystem", "clanMembers", null);
    }

    public int getOffset() {
        return (int)AppletLoader.getSingleton().getFieldValue("AbstractSoundSystem", "offset", ref);
    }

    public static int getPriority() {
        return (int)AppletLoader.getSingleton().getFieldValue("AbstractSoundSystem", "priority", null);
    }

    public static int getSampleRate() {
        return (int)AppletLoader.getSingleton().getFieldValue("AbstractSoundSystem", "sampleRate", null);
    }

    public int[] getSamples() {
        return (int[])AppletLoader.getSingleton().getFieldValue("AbstractSoundSystem", "samples", ref);
    }

}
