/*
 * RSAbstractIntegerNode0.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: dy => gw (Node) => java.lang.Object
public class RSAbstractIntegerNode0 extends RSNode {

    public RSAbstractIntegerNode0(Object ref) {
        super(ref);
    }

    public int getInt1() {
        return (int)AppletLoader.getSingleton().getFieldValue("AbstractIntegerNode0", "int1", ref);
    }

}
