/*
 * RSBoundingBox.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: f => gw (Node) => java.lang.Object
public class RSBoundingBox extends RSNode {

    public RSBoundingBox(Object ref) {
        super(ref);
    }

}
