/*
 * RSBufferProvider.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: kr => java.lang.Object
public class RSBufferProvider extends RSClassWrapper {

    public RSBufferProvider(Object ref) {
        super(ref);
    }

    public int[] getPixels() {
        return (int[])AppletLoader.getSingleton().getFieldValue("BufferProvider", "pixels", ref);
    }

    public int getWidth() {
        return (int)AppletLoader.getSingleton().getFieldValue("BufferProvider", "width", ref);
    }

    public int getHeight() {
        return (int)AppletLoader.getSingleton().getFieldValue("BufferProvider", "height", ref);
    }

}
