/*
 * RSBuffer.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: gv => gw (Node) => java.lang.Object
public class RSBuffer extends RSNode {

    public RSBuffer(Object ref) {
        super(ref);
    }

    public static long[] getCrc64Table() {
        return (long[])AppletLoader.getSingleton().getFieldValue("Buffer", "crc64Table", null);
    }

    public int getOffset() {
        return (int)AppletLoader.getSingleton().getFieldValue("Buffer", "offset", ref);
    }

    public byte[] getPayload() {
        return (byte[])AppletLoader.getSingleton().getFieldValue("Buffer", "payload", ref);
    }

    public static int[] getCrc32Table() {
        return (int[])AppletLoader.getSingleton().getFieldValue("Buffer", "crc32Table", null);
    }

}
