/*
 * RSByteArrayNode.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: hk => gw (Node) => java.lang.Object
public class RSByteArrayNode extends RSNode {

    public RSByteArrayNode(Object ref) {
        super(ref);
    }

    public byte[] getByteArray() {
        return (byte[])AppletLoader.getSingleton().getFieldValue("ByteArrayNode", "byteArray", ref);
    }

}
