/*
 * RSCacheableNode.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: gd => gw (Node) => java.lang.Object
public class RSCacheableNode extends RSNode {

    public RSCacheableNode(Object ref) {
        super(ref);
    }

    public RSCacheableNode getNext() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("CacheableNode", "next", ref);
        RSCacheableNode wrappers = null;
        if(objects != null)
            wrappers = (RSCacheableNode)getWrapper(objects);
        return wrappers;
    }

    public RSCacheableNode getPrevious() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("CacheableNode", "previous", ref);
        RSCacheableNode wrappers = null;
        if(objects != null)
            wrappers = (RSCacheableNode)getWrapper(objects);
        return wrappers;
    }

}
