/*
 * RSCanvas.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: bc => java.awt.Canvas
public class RSCanvas extends RSClassWrapper {

    public RSCanvas(Object ref) {
        super(ref);
    }

    public java.awt.Component getComponent() {
        return (java.awt.Component)AppletLoader.getSingleton().getFieldValue("RSCanvas", "component", ref);
    }

}
