/*
 * RSCacheFile.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: dm => java.lang.Object
public class RSCacheFile extends RSClassWrapper {

    public RSCacheFile(Object ref) {
        super(ref);
    }

    public byte[] getReadPayload() {
        return (byte[])AppletLoader.getSingleton().getFieldValue("CacheFile", "readPayload", ref);
    }

    public byte[] getWritePayload() {
        return (byte[])AppletLoader.getSingleton().getFieldValue("CacheFile", "writePayload", ref);
    }

    public RSFileOnDisk getAccessFile() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("CacheFile", "accessFile", ref);
        RSFileOnDisk wrappers = null;
        if(objects != null)
            wrappers = (RSFileOnDisk)getWrapper(objects);
        return wrappers;
    }

    public long getLength() {
        return (long)AppletLoader.getSingleton().getFieldValue("CacheFile", "length", ref);
    }

    public long getPosition() {
        return (long)AppletLoader.getSingleton().getFieldValue("CacheFile", "position", ref);
    }

    public long getCapacity() {
        return (long)AppletLoader.getSingleton().getFieldValue("CacheFile", "capacity", ref);
    }

}
