/*
 * RSChatLineBuffer.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ci => java.lang.Object
public class RSChatLineBuffer extends RSClassWrapper {

    public RSChatLineBuffer(Object ref) {
        super(ref);
    }

    public int getLength() {
        return (int)AppletLoader.getSingleton().getFieldValue("ChatLineBuffer", "length", ref);
    }

    public RSMessageNode[] getLines() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("ChatLineBuffer", "lines", ref);
        RSMessageNode[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSMessageNode[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSMessageNode)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public Object[] getRSRef_Lines() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("ChatLineBuffer", "lines", ref);
    }

}
