/*
 * RSClass222.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: hn => java.lang.Object
public class RSClass222 extends RSClassWrapper {

    public RSClass222(Object ref) {
        super(ref);
    }

    public static int[] getWidgetSettings() {
        return (int[])AppletLoader.getSingleton().getFieldValue("class222", "widgetSettings", null);
    }

    public static int[] getSettings() {
        return (int[])AppletLoader.getSingleton().getFieldValue("class222", "settings", null);
    }

    public static int[] getVarpsMasks() {
        return (int[])AppletLoader.getSingleton().getFieldValue("class222", "varpsMasks", null);
    }

}
