/*
 * RSClass25.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: q => java.lang.Object
public class RSClass25 extends RSClassWrapper {

    public RSClass25(Object ref) {
        super(ref);
    }

    public static RSClass159 getRssocket() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class25", "rssocket", null);
        RSClass159 wrappers = null;
        if(objects != null)
            wrappers = (RSClass159)getWrapper(objects);
        return wrappers;
    }

    public static int getCanvasHeight() {
        return (int)AppletLoader.getSingleton().getFieldValue("class25", "canvasHeight", null);
    }

}
