/*
 * RSClientPacket.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: fj => java.lang.Object
public class RSClientPacket extends RSClassWrapper {

    public RSClientPacket(Object ref) {
        super(ref);
    }

    public int getPacketId() {
        return (int)AppletLoader.getSingleton().getFieldValue("ClientPacket", "packetId", ref);
    }

    public int getPacketLength() {
        return (int)AppletLoader.getSingleton().getFieldValue("ClientPacket", "packetLength", ref);
    }

}
