/*
 * RSClass111.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: de => java.lang.Object
public class RSClass111 extends RSClassWrapper {

    public RSClass111(Object ref) {
        super(ref);
    }

    public RSIndexDataBase getSfx_index() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class111", "sfx_index", ref);
        RSIndexDataBase wrappers = null;
        if(objects != null)
            wrappers = (RSIndexDataBase)getWrapper(objects);
        return wrappers;
    }

    public RSIndexDataBase getVorbis_index() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class111", "vorbis_index", ref);
        RSIndexDataBase wrappers = null;
        if(objects != null)
            wrappers = (RSIndexDataBase)getWrapper(objects);
        return wrappers;
    }

}
