/*
 * RSClass91.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: cz => java.lang.Object
public class RSClass91 extends RSClassWrapper {

    public RSClass91(Object ref) {
        super(ref);
    }

    public static java.lang.String getLoadingText() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("class91", "loadingText", null);
    }

    public static RSIndexedSprite getLogoSprite() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class91", "logoSprite", null);
        RSIndexedSprite wrappers = null;
        if(objects != null)
            wrappers = (RSIndexedSprite)getWrapper(objects);
        return wrappers;
    }

    public static RSIndexedSprite[] getRuneSprites() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("class91", "runeSprites", null);
        RSIndexedSprite[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSIndexedSprite[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSIndexedSprite)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public static Object[] getRSRef_RuneSprites() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("class91", "runeSprites", null);
    }

    public static int getLoginWindowX() {
        return (int)AppletLoader.getSingleton().getFieldValue("class91", "loginWindowX", null);
    }

    public static int getLoadingBarPercentage() {
        return (int)AppletLoader.getSingleton().getFieldValue("class91", "loadingBarPercentage", null);
    }

}
