/*
 * RSClass37.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ah => java.lang.Object
public class RSClass37 extends RSClassWrapper {

    public RSClass37(Object ref) {
        super(ref);
    }

    public static RSUrlRequest getListFetcher() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class37", "listFetcher", null);
        RSUrlRequest wrappers = null;
        if(objects != null)
            wrappers = (RSUrlRequest)getWrapper(objects);
        return wrappers;
    }

}
