/*
 * RSClass235.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ib => java.lang.Object
public class RSClass235 extends RSClassWrapper {

    public RSClass235(Object ref) {
        super(ref);
    }

    public static int[] getLandMapFileIds() {
        return (int[])AppletLoader.getSingleton().getFieldValue("class235", "landMapFileIds", null);
    }

}
