/*
 * RSClass299.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: kd => java.lang.Object
public class RSClass299 extends RSClassWrapper {

    public RSClass299(Object ref) {
        super(ref);
    }

    public static int[] getOffsetsY() {
        return (int[])AppletLoader.getSingleton().getFieldValue("class299", "offsetsY", null);
    }

}
