/*
 * RSClass45.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: ak => at (class28) => java.lang.Object
public class RSClass45 extends RSClass28 {

    public RSClass45(Object ref) {
        super(ref);
    }

    public static boolean getMiddleMouseMovesCamera() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("class45", "middleMouseMovesCamera", null);
    }

}
