/*
 * RSClass277.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: jg => java.lang.Object
public class RSClass277 extends RSClassWrapper {

    public RSClass277(Object ref) {
        super(ref);
    }

    public static char[] getCp1252AsciiExtension() {
        return (char[])AppletLoader.getSingleton().getFieldValue("class277", "cp1252AsciiExtension", null);
    }

}
