/*
 * RSClass101.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: ca => dk (TaskDataNode) => gw (Node) => java.lang.Object
public class RSClass101 extends RSTaskDataNode {

    public RSClass101(Object ref) {
        super(ref);
    }

}
