/*
 * RSClass48.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: an => java.lang.Object
public class RSClass48 extends RSClassWrapper {

    public RSClass48(Object ref) {
        super(ref);
    }

    public static RSFonts getFonts() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class48", "fonts", null);
        RSFonts wrappers = null;
        if(objects != null)
            wrappers = (RSFonts)getWrapper(objects);
        return wrappers;
    }

}
