/*
 * RSClass33.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ae => java.lang.Object
public class RSClass33 extends RSClassWrapper {

    public RSClass33(Object ref) {
        super(ref);
    }

}
