/*
 * RSClass188.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: gn => java.lang.Object
public class RSClass188 extends RSClassWrapper {

    public RSClass188(Object ref) {
        super(ref);
    }

    public static byte[][] getSpritePixels() {
        return (byte[][])AppletLoader.getSingleton().getFieldValue("class188", "spritePixels", null);
    }

}
