/*
 * RSClass254.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: ix => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSClass254 extends RSCacheableNode {

    public RSClass254(Object ref) {
        super(ref);
    }

    public static boolean[] getValidInterfaces() {
        return (boolean[])AppletLoader.getSingleton().getFieldValue("class254", "validInterfaces", null);
    }

    public static RSIndexedSprite[] getModIconSprites() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("class254", "modIconSprites", null);
        RSIndexedSprite[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSIndexedSprite[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSIndexedSprite)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public static Object[] getRSRef_ModIconSprites() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("class254", "modIconSprites", null);
    }

}
