/*
 * RSClass2.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: y => java.lang.Object
public class RSClass2 extends RSClassWrapper {

    public RSClass2(Object ref) {
        super(ref);
    }

    public static boolean getHighMemory() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("class2", "highMemory", null);
    }

    public static RSSpritePixels getMapedge() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class2", "mapedge", null);
        RSSpritePixels wrappers = null;
        if(objects != null)
            wrappers = (RSSpritePixels)getWrapper(objects);
        return wrappers;
    }

}
