/*
 * RSClass186.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ge => java.lang.Object
public class RSClass186 extends RSClassWrapper {

    public RSClass186(Object ref) {
        super(ref);
    }

    public static long getCurrentTimeMsOffset() {
        return (long)AppletLoader.getSingleton().getFieldValue("class186", "currentTimeMsOffset", null);
    }

    public static long getCurrentTimeMsLast() {
        return (long)AppletLoader.getSingleton().getFieldValue("class186", "currentTimeMsLast", null);
    }

}
