/*
 * RSClassInfo.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: ka => gw (Node) => java.lang.Object
public class RSClassInfo extends RSNode {

    public RSClassInfo(Object ref) {
        super(ref);
    }

    public byte[][][] getArgs() {
        return (byte[][][])AppletLoader.getSingleton().getFieldValue("ClassInfo", "args", ref);
    }

    public int[] getErrorIdentifiers() {
        return (int[])AppletLoader.getSingleton().getFieldValue("ClassInfo", "errorIdentifiers", ref);
    }

    public java.lang.reflect.Method[] getMethods() {
        return (java.lang.reflect.Method[])AppletLoader.getSingleton().getFieldValue("ClassInfo", "methods", ref);
    }

    public int getCount() {
        return (int)AppletLoader.getSingleton().getFieldValue("ClassInfo", "count", ref);
    }

    public int[] getType() {
        return (int[])AppletLoader.getSingleton().getFieldValue("ClassInfo", "type", ref);
    }

    public java.lang.reflect.Field[] getFields() {
        return (java.lang.reflect.Field[])AppletLoader.getSingleton().getFieldValue("ClassInfo", "fields", ref);
    }

}
