/*
 * RSClass96.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: cm => java.lang.Object
public class RSClass96 extends RSClassWrapper {

    public RSClass96(Object ref) {
        super(ref);
    }

    public static java.util.Map getChatLineMap() {
        return (java.util.Map)AppletLoader.getSingleton().getFieldValue("class96", "chatLineMap", null);
    }

    public static RSIterableHashTable getMessages() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class96", "messages", null);
        RSIterableHashTable wrappers = null;
        if(objects != null)
            wrappers = (RSIterableHashTable)getWrapper(objects);
        return wrappers;
    }

}
