/*
 * RSClass22.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: g => at (class28) => java.lang.Object
public class RSClass22 extends RSClass28 {

    public RSClass22(Object ref) {
        super(ref);
    }

}
