/*
 * RSClass215.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: hu => dk (TaskDataNode) => gw (Node) => java.lang.Object
public class RSClass215 extends RSTaskDataNode {

    public RSClass215(Object ref) {
        super(ref);
    }

    public static RSIndexData getConfigsIndex() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class215", "configsIndex", null);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

}
