/*
 * RSClass7.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: b => java.lang.Object
public class RSClass7 extends RSClassWrapper {

    public RSClass7(Object ref) {
        super(ref);
    }

    public static RSCombatInfoList getBoundingBoxes() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class7", "boundingBoxes", null);
        RSCombatInfoList wrappers = null;
        if(objects != null)
            wrappers = (RSCombatInfoList)getWrapper(objects);
        return wrappers;
    }

    public static RSClass11 getBoundingBox3DDrawMode() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class7", "boundingBox3DDrawMode", null);
        RSClass11 wrappers = null;
        if(objects != null)
            wrappers = (RSClass11)getWrapper(objects);
        return wrappers;
    }

    public static boolean getDrawBoundingBoxes3D() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("class7", "drawBoundingBoxes3D", null);
    }

    public static boolean getDrawBoundingBoxes2D() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("class7", "drawBoundingBoxes2D", null);
    }

    public static boolean getDrawObjectGeometry2D() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("class7", "drawObjectGeometry2D", null);
    }

}
