/*
 * RSClass19.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: x => java.lang.Object
public class RSClass19 extends RSClassWrapper {

    public RSClass19(Object ref) {
        super(ref);
    }

    public static RSIndexData getIndexCache4() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class19", "indexCache4", null);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

}
