/*
 * RSClanMember.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: br => gw (Node) => java.lang.Object
public class RSClanMember extends RSNode {

    public RSClanMember(Object ref) {
        super(ref);
    }

    public int getWorld() {
        return (int)AppletLoader.getSingleton().getFieldValue("ClanMember", "world", ref);
    }

    public byte getRank() {
        return (byte)AppletLoader.getSingleton().getFieldValue("ClanMember", "rank", ref);
    }

    public java.lang.String getUsername() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("ClanMember", "username", ref);
    }

}
