/*
 * RSClass305.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: kv => java.lang.Object
public class RSClass305 extends RSClassWrapper {

    public RSClass305(Object ref) {
        super(ref);
    }

}
