/*
 * RSClass35.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: am => java.lang.Object
public class RSClass35 extends RSClassWrapper {

    public RSClass35(Object ref) {
        super(ref);
    }

    public static RSBufferProvider getRasterProvider() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class35", "rasterProvider", null);
        RSBufferProvider wrappers = null;
        if(objects != null)
            wrappers = (RSBufferProvider)getWrapper(objects);
        return wrappers;
    }

}
