/*
 * RSClass27.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: aw => java.lang.Object
public class RSClass27 extends RSClassWrapper {

    public RSClass27(Object ref) {
        super(ref);
    }

}
