/*
 * RSClass161.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: fs => fl (class159) => java.lang.Object
public class RSClass161 extends RSClass159 {

    public RSClass161(Object ref) {
        super(ref);
    }

    public static java.lang.String getHost() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("class161", "host", null);
    }

}
