/*
 * RSClass262.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: ja => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSClass262 extends RSCacheableNode {

    public RSClass262(Object ref) {
        super(ref);
    }

}
