/*
 * RSClass36.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ax => java.lang.Object
public class RSClass36 extends RSClassWrapper {

    public RSClass36(Object ref) {
        super(ref);
    }

    public static RSFont getFontBold12() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class36", "fontBold12", null);
        RSFont wrappers = null;
        if(objects != null)
            wrappers = (RSFont)getWrapper(objects);
        return wrappers;
    }

}
