/*
 * RSClass218.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: hm => gw (Node) => java.lang.Object
public class RSClass218 extends RSNode {

    public RSClass218(Object ref) {
        super(ref);
    }

}
