/*
 * RSClass153.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ec => java.lang.Object
public class RSClass153 extends RSClassWrapper {

    public RSClass153(Object ref) {
        super(ref);
    }

    public static java.lang.String getUserHome() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("class153", "userHome", null);
    }

    public static RSTask getSocket() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class153", "socket", null);
        RSTask wrappers = null;
        if(objects != null)
            wrappers = (RSTask)getWrapper(objects);
        return wrappers;
    }

}
