/*
 * RSClass87.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: cu => java.lang.Object
public class RSClass87 extends RSClassWrapper {

    public RSClass87(Object ref) {
        super(ref);
    }

    public static int getCanvasWidth() {
        return (int)AppletLoader.getSingleton().getFieldValue("class87", "canvasWidth", null);
    }

}
