/*
 * RSClass72.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: bh => fo (class168) => java.lang.Object
public class RSClass72 extends RSClass168 {

    public RSClass72(Object ref) {
        super(ref);
    }

}
