/*
 * RSClass249.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: iw => java.lang.Object
public class RSClass249 extends RSClassWrapper {

    public RSClass249(Object ref) {
        super(ref);
    }

    public static java.util.zip.CRC32 getNetCache_crc() {
        return (java.util.zip.CRC32)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_crc", null);
    }

    public static int getNetCache_pendingResponsesCount() {
        return (int)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_pendingResponsesCount", null);
    }

    public static RSHashTable getNetCache_pendingResponses() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_pendingResponses", null);
        RSHashTable wrappers = null;
        if(objects != null)
            wrappers = (RSHashTable)getWrapper(objects);
        return wrappers;
    }

    public static int getNetCache_pendingPriorityWritesCount() {
        return (int)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_pendingPriorityWritesCount", null);
    }

    public static RSIndexData[] getNetCache_indexCaches() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("class249", "NetCache_indexCaches", null);
        RSIndexData[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSIndexData[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSIndexData)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public static Object[] getRSRef_NetCache_indexCaches() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("class249", "NetCache_indexCaches", null);
    }

    public static RSHashTable getNetCache_pendingPriorityWrites() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_pendingPriorityWrites", null);
        RSHashTable wrappers = null;
        if(objects != null)
            wrappers = (RSHashTable)getWrapper(objects);
        return wrappers;
    }

    public static RSHashTable getNetCache_pendingWrites() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_pendingWrites", null);
        RSHashTable wrappers = null;
        if(objects != null)
            wrappers = (RSHashTable)getWrapper(objects);
        return wrappers;
    }

    public static RSClass159 getNetCache_socket() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_socket", null);
        RSClass159 wrappers = null;
        if(objects != null)
            wrappers = (RSClass159)getWrapper(objects);
        return wrappers;
    }

    public static RSHashTable getNetCache_pendingPriorityResponses() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_pendingPriorityResponses", null);
        RSHashTable wrappers = null;
        if(objects != null)
            wrappers = (RSHashTable)getWrapper(objects);
        return wrappers;
    }

    public static int getNetCache_pendingWritesCount() {
        return (int)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_pendingWritesCount", null);
    }

    public static RSBuffer getNetCache_responseHeaderBuffer() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_responseHeaderBuffer", null);
        RSBuffer wrappers = null;
        if(objects != null)
            wrappers = (RSBuffer)getWrapper(objects);
        return wrappers;
    }

    public static RSNode2LinkedList getNetCache_pendingWritesQueue() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_pendingWritesQueue", null);
        RSNode2LinkedList wrappers = null;
        if(objects != null)
            wrappers = (RSNode2LinkedList)getWrapper(objects);
        return wrappers;
    }

    public static int getNetCache_pendingPriorityResponsesCount() {
        return (int)AppletLoader.getSingleton().getFieldValue("class249", "NetCache_pendingPriorityResponsesCount", null);
    }

}
