/*
 * RSClass234.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: is => java.lang.Object
public class RSClass234 extends RSClassWrapper {

    public RSClass234(Object ref) {
        super(ref);
    }

    public static RSSpritePixels getMinimapSprite() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class234", "minimapSprite", null);
        RSSpritePixels wrappers = null;
        if(objects != null)
            wrappers = (RSSpritePixels)getWrapper(objects);
        return wrappers;
    }

}
