/*
 * RSClass157.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: fr => java.lang.Object
public class RSClass157 extends RSClassWrapper {

    public RSClass157(Object ref) {
        super(ref);
    }

    public static RSCacheFile getDat2File() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class157", "dat2File", null);
        RSCacheFile wrappers = null;
        if(objects != null)
            wrappers = (RSCacheFile)getWrapper(objects);
        return wrappers;
    }

    public static RSCacheFile[] getIdxFiles() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("class157", "idxFiles", null);
        RSCacheFile[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSCacheFile[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSCacheFile)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public static Object[] getRSRef_IdxFiles() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("class157", "idxFiles", null);
    }

    public static java.lang.String getOsNameLC() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("class157", "osNameLC", null);
    }

    public static java.io.File getJagexClDat() {
        return (java.io.File)AppletLoader.getSingleton().getFieldValue("class157", "jagexClDat", null);
    }

    public static int getIdxCount() {
        return (int)AppletLoader.getSingleton().getFieldValue("class157", "idxCount", null);
    }

    public static RSCacheFile getRandomDat() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class157", "randomDat", null);
        RSCacheFile wrappers = null;
        if(objects != null)
            wrappers = (RSCacheFile)getWrapper(objects);
        return wrappers;
    }

    public static RSCacheFile getIdx255File() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class157", "idx255File", null);
        RSCacheFile wrappers = null;
        if(objects != null)
            wrappers = (RSCacheFile)getWrapper(objects);
        return wrappers;
    }

}
