/*
 * RSClass179.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: fw => java.lang.Object
public class RSClass179 extends RSClassWrapper {

    public RSClass179(Object ref) {
        super(ref);
    }

    public static int getMyWorldPort() {
        return (int)AppletLoader.getSingleton().getFieldValue("class179", "myWorldPort", null);
    }

    public static RSSignlink getTaskManager() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class179", "taskManager", null);
        RSSignlink wrappers = null;
        if(objects != null)
            wrappers = (RSSignlink)getWrapper(objects);
        return wrappers;
    }

}
