/*
 * RSClass281.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ja => java.lang.Object
public class RSClass281 extends RSClassWrapper {

    public RSClass281(Object ref) {
        super(ref);
    }

    public static int[] getScriptLocalInts() {
        return (int[])AppletLoader.getSingleton().getFieldValue("class281", "scriptLocalInts", null);
    }

}
