/*
 * RSClass3.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: r => java.lang.Object
public class RSClass3 extends RSClassWrapper {

    public RSClass3(Object ref) {
        super(ref);
    }

    public static RSIndexData getIndexTextures() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class3", "indexTextures", null);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

}
