/*
 * RSClass160.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ft => java.lang.Object
public class RSClass160 extends RSClassWrapper {

    public RSClass160(Object ref) {
        super(ref);
    }

    public static RSTaskDataProvider getSoundTaskDataProvider() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class160", "soundTaskDataProvider", null);
        RSTaskDataProvider wrappers = null;
        if(objects != null)
            wrappers = (RSTaskDataProvider)getWrapper(objects);
        return wrappers;
    }

}
