/*
 * RSClass159.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: fl => java.lang.Object
public class RSClass159 extends RSClassWrapper {

    public RSClass159(Object ref) {
        super(ref);
    }

    public static RSVarcs getChatMessages() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class159", "chatMessages", null);
        RSVarcs wrappers = null;
        if(objects != null)
            wrappers = (RSVarcs)getWrapper(objects);
        return wrappers;
    }

}
