/*
 * RSClass231.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ha => java.lang.Object
public class RSClass231 extends RSClassWrapper {

    public RSClass231(Object ref) {
        super(ref);
    }

    public static RSBuffer getNetCache_responseArchiveBuffer() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class231", "NetCache_responseArchiveBuffer", null);
        RSBuffer wrappers = null;
        if(objects != null)
            wrappers = (RSBuffer)getWrapper(objects);
        return wrappers;
    }

}
