/*
 * RSClass21.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: j => java.lang.Object
public class RSClass21 extends RSClassWrapper {

    public RSClass21(Object ref) {
        super(ref);
    }

    public static RSIndexedSprite[] getMapscene() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("class21", "mapscene", null);
        RSIndexedSprite[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSIndexedSprite[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSIndexedSprite)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public static Object[] getRSRef_Mapscene() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("class21", "mapscene", null);
    }

}
