/*
 * RSClass163.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: fu => fl (class159) => java.lang.Object
public class RSClass163 extends RSClass159 {

    public RSClass163(Object ref) {
        super(ref);
    }

}
