/*
 * RSClass276.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: jw => java.lang.Object
public class RSClass276 extends RSClassWrapper {

    public RSClass276(Object ref) {
        super(ref);
    }

    public static RSHuffman getHuffman() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("class276", "huffman", null);
        RSHuffman wrappers = null;
        if(objects != null)
            wrappers = (RSHuffman)getWrapper(objects);
        return wrappers;
    }

}
