/*
 * RSClass81.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: cl => gw (Node) => java.lang.Object
public class RSClass81 extends RSNode {

    public RSClass81(Object ref) {
        super(ref);
    }

}
