/*
 * RSContextMenuRow.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: cf => java.lang.Object
public class RSContextMenuRow extends RSClassWrapper {

    public RSContextMenuRow(Object ref) {
        super(ref);
    }

    public int getIdentifier() {
        return (int)AppletLoader.getSingleton().getFieldValue("ContextMenuRow", "identifier", ref);
    }

    public int getParam0() {
        return (int)AppletLoader.getSingleton().getFieldValue("ContextMenuRow", "param0", ref);
    }

    public int getType() {
        return (int)AppletLoader.getSingleton().getFieldValue("ContextMenuRow", "type", ref);
    }

    public int getParam1() {
        return (int)AppletLoader.getSingleton().getFieldValue("ContextMenuRow", "param1", ref);
    }

    public java.lang.String getOption() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("ContextMenuRow", "option", ref);
    }

}
