/*
 * RSCollisionData.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: fi => java.lang.Object
public class RSCollisionData extends RSClassWrapper {

    public RSCollisionData(Object ref) {
        super(ref);
    }

    public int[][] getFlags() {
        return (int[][])AppletLoader.getSingleton().getFieldValue("CollisionData", "flags", ref);
    }

    public int getWidth() {
        return (int)AppletLoader.getSingleton().getFieldValue("CollisionData", "width", ref);
    }

    public int getX() {
        return (int)AppletLoader.getSingleton().getFieldValue("CollisionData", "x", ref);
    }

    public int getY() {
        return (int)AppletLoader.getSingleton().getFieldValue("CollisionData", "y", ref);
    }

    public int getHeight() {
        return (int)AppletLoader.getSingleton().getFieldValue("CollisionData", "height", ref);
    }

}
