/*
 * RSCombatInfoList.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: gs => java.lang.Object
public class RSCombatInfoList extends RSClassWrapper {

    public RSCombatInfoList(Object ref) {
        super(ref);
    }

    public RSNode getNode() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("CombatInfoList", "node", ref);
        RSNode wrappers = null;
        if(objects != null)
            wrappers = (RSNode)getWrapper(objects);
        return wrappers;
    }

    public RSNode getCurrent() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("CombatInfoList", "current", ref);
        RSNode wrappers = null;
        if(objects != null)
            wrappers = (RSNode)getWrapper(objects);
        return wrappers;
    }

}
