/*
 * RSCodeBook.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: co => java.lang.Object
public class RSCodeBook extends RSClassWrapper {

    public RSCodeBook(Object ref) {
        super(ref);
    }

    public int[] getEntryLengths() {
        return (int[])AppletLoader.getSingleton().getFieldValue("CodeBook", "entryLengths", ref);
    }

    public int getEntries() {
        return (int)AppletLoader.getSingleton().getFieldValue("CodeBook", "entries", ref);
    }

    public float[][] getValueVector() {
        return (float[][])AppletLoader.getSingleton().getFieldValue("CodeBook", "valueVector", ref);
    }

    public int getDimensions() {
        return (int)AppletLoader.getSingleton().getFieldValue("CodeBook", "dimensions", ref);
    }

}
