/*
 * RSCombatInfo1.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: cj => gw (Node) => java.lang.Object
public class RSCombatInfo1 extends RSNode {

    public RSCombatInfo1(Object ref) {
        super(ref);
    }

    public int getInt2() {
        return (int)AppletLoader.getSingleton().getFieldValue("CombatInfo1", "int2", ref);
    }

    public int getHealthRatio() {
        return (int)AppletLoader.getSingleton().getFieldValue("CombatInfo1", "healthRatio", ref);
    }

    public int getHealth() {
        return (int)AppletLoader.getSingleton().getFieldValue("CombatInfo1", "health", ref);
    }

    public static RSFont getFont_p12full() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("CombatInfo1", "font_p12full", null);
        RSFont wrappers = null;
        if(objects != null)
            wrappers = (RSFont)getWrapper(objects);
        return wrappers;
    }

    public int getCycle() {
        return (int)AppletLoader.getSingleton().getFieldValue("CombatInfo1", "cycle", ref);
    }

}
