/*
 * RSCoordinates.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ht => java.lang.Object
public class RSCoordinates extends RSClassWrapper {

    public RSCoordinates(Object ref) {
        super(ref);
    }

    public int getPlane() {
        return (int)AppletLoader.getSingleton().getFieldValue("Coordinates", "plane", ref);
    }

    public int getWorldX() {
        return (int)AppletLoader.getSingleton().getFieldValue("Coordinates", "worldX", ref);
    }

    public int getWorldY() {
        return (int)AppletLoader.getSingleton().getFieldValue("Coordinates", "worldY", ref);
    }

}
