/*
 * RSDeque.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: gi => java.lang.Object
public class RSDeque extends RSClassWrapper {

    public RSDeque(Object ref) {
        super(ref);
    }

    public RSNode getHead() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Deque", "head", ref);
        RSNode wrappers = null;
        if(objects != null)
            wrappers = (RSNode)getWrapper(objects);
        return wrappers;
    }

    public RSNode getCurrent() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Deque", "current", ref);
        RSNode wrappers = null;
        if(objects != null)
            wrappers = (RSNode)getWrapper(objects);
        return wrappers;
    }

}
