/*
 * RSDynamicObject.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: ce => eo (Renderable) => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSDynamicObject extends RSRenderable {

    public RSDynamicObject(Object ref) {
        super(ref);
    }

    public int getSceneY() {
        return (int)AppletLoader.getSingleton().getFieldValue("DynamicObject", "sceneY", ref);
    }

    public int getOrientation() {
        return (int)AppletLoader.getSingleton().getFieldValue("DynamicObject", "orientation", ref);
    }

    public int getSceneX() {
        return (int)AppletLoader.getSingleton().getFieldValue("DynamicObject", "sceneX", ref);
    }

    public int getLevel() {
        return (int)AppletLoader.getSingleton().getFieldValue("DynamicObject", "level", ref);
    }

    public int getId() {
        return (int)AppletLoader.getSingleton().getFieldValue("DynamicObject", "id", ref);
    }

    public int getType() {
        return (int)AppletLoader.getSingleton().getFieldValue("DynamicObject", "type", ref);
    }

}
