/*
 * RSFaceNormal.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ev => java.lang.Object
public class RSFaceNormal extends RSClassWrapper {

    public RSFaceNormal(Object ref) {
        super(ref);
    }

    public int getX() {
        return (int)AppletLoader.getSingleton().getFieldValue("FaceNormal", "x", ref);
    }

    public int getY() {
        return (int)AppletLoader.getSingleton().getFieldValue("FaceNormal", "y", ref);
    }

    public int getZ() {
        return (int)AppletLoader.getSingleton().getFieldValue("FaceNormal", "z", ref);
    }

}
