/*
 * RSFileSystem.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: iq => gw (Node) => java.lang.Object
public class RSFileSystem extends RSNode {

    public RSFileSystem(Object ref) {
        super(ref);
    }

    public RSIndexData getData() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("FileSystem", "data", ref);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

    public static int getClanChatCount() {
        return (int)AppletLoader.getSingleton().getFieldValue("FileSystem", "clanChatCount", null);
    }

    public RSIndexFile getIndex() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("FileSystem", "index", ref);
        RSIndexFile wrappers = null;
        if(objects != null)
            wrappers = (RSIndexFile)getWrapper(objects);
        return wrappers;
    }

    public int getType() {
        return (int)AppletLoader.getSingleton().getFieldValue("FileSystem", "type", ref);
    }

}
