/*
 * RSFileRequest.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: it => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSFileRequest extends RSCacheableNode {

    public RSFileRequest(Object ref) {
        super(ref);
    }

    public byte getPadding() {
        return (byte)AppletLoader.getSingleton().getFieldValue("FileRequest", "padding", ref);
    }

    public int getCrc() {
        return (int)AppletLoader.getSingleton().getFieldValue("FileRequest", "crc", ref);
    }

    public static RSFont getFontPlain11() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("FileRequest", "fontPlain11", null);
        RSFont wrappers = null;
        if(objects != null)
            wrappers = (RSFont)getWrapper(objects);
        return wrappers;
    }

    public RSIndexData getIndex() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("FileRequest", "index", ref);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

}
