/*
 * RSFonts.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: jk => java.lang.Object
public class RSFonts extends RSClassWrapper {

    public RSFonts(Object ref) {
        super(ref);
    }

    public java.util.HashMap getMap() {
        return (java.util.HashMap)AppletLoader.getSingleton().getFieldValue("Fonts", "map", ref);
    }

}
