/*
 * RSFrames.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: ek => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSFrames extends RSCacheableNode {

    public RSFrames(Object ref) {
        super(ref);
    }

    public RSFrame[] getSkeletons() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("Frames", "skeletons", ref);
        RSFrame[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSFrame[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSFrame)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public Object[] getRSRef_Skeletons() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("Frames", "skeletons", ref);
    }

    public static int getPort1() {
        return (int)AppletLoader.getSingleton().getFieldValue("Frames", "port1", null);
    }

}
