/*
 * RSFriend.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ba => java.lang.Object
public class RSFriend extends RSClassWrapper {

    public RSFriend(Object ref) {
        super(ref);
    }

    public int getWorld() {
        return (int)AppletLoader.getSingleton().getFieldValue("Friend", "world", ref);
    }

    public java.lang.String getPreviousName() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("Friend", "previousName", ref);
    }

    public java.lang.String getName() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("Friend", "name", ref);
    }

    public int getRank() {
        return (int)AppletLoader.getSingleton().getFieldValue("Friend", "rank", ref);
    }

}
