/*
 * RSFrame.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: eu => java.lang.Object
public class RSFrame extends RSClassWrapper {

    public RSFrame(Object ref) {
        super(ref);
    }

    public int[] getTranslator_z() {
        return (int[])AppletLoader.getSingleton().getFieldValue("Frame", "translator_z", ref);
    }

    public int[] getTranslator_y() {
        return (int[])AppletLoader.getSingleton().getFieldValue("Frame", "translator_y", ref);
    }

    public int[] getTranslator_x() {
        return (int[])AppletLoader.getSingleton().getFieldValue("Frame", "translator_x", ref);
    }

    public RSFrameMap getSkin() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Frame", "skin", ref);
        RSFrameMap wrappers = null;
        if(objects != null)
            wrappers = (RSFrameMap)getWrapper(objects);
        return wrappers;
    }

    public boolean getShowing() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("Frame", "showing", ref);
    }

}
