/*
 * RSFrameMap.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: ei => gw (Node) => java.lang.Object
public class RSFrameMap extends RSNode {

    public RSFrameMap(Object ref) {
        super(ref);
    }

    public int[] getTypes() {
        return (int[])AppletLoader.getSingleton().getFieldValue("FrameMap", "types", ref);
    }

    public int getCount() {
        return (int)AppletLoader.getSingleton().getFieldValue("FrameMap", "count", ref);
    }

    public int getId() {
        return (int)AppletLoader.getSingleton().getFieldValue("FrameMap", "id", ref);
    }

    public int[][] getList() {
        return (int[][])AppletLoader.getSingleton().getFieldValue("FrameMap", "list", ref);
    }

}
