/*
 * RSGameCanvas.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: bq => java.awt.Canvas
public class RSGameCanvas extends RSClassWrapper {

    public RSGameCanvas(Object ref) {
        super(ref);
    }

    public java.awt.Component getComponent() {
        return (java.awt.Component)AppletLoader.getSingleton().getFieldValue("GameCanvas", "component", ref);
    }

    public static RSIndexData getIndexWorldMap() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("GameCanvas", "indexWorldMap", null);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

}
