/*
 * RSGroundObject.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ds => java.lang.Object
public class RSGroundObject extends RSClassWrapper {

    public RSGroundObject(Object ref) {
        super(ref);
    }

    public RSRenderable getRenderable() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("GroundObject", "renderable", ref);
        RSRenderable wrappers = null;
        if(objects != null)
            wrappers = (RSRenderable)getWrapper(objects);
        return wrappers;
    }

    public int getX() {
        return (int)AppletLoader.getSingleton().getFieldValue("GroundObject", "x", ref);
    }

    public int getY() {
        return (int)AppletLoader.getSingleton().getFieldValue("GroundObject", "y", ref);
    }

    public int getFloor() {
        return (int)AppletLoader.getSingleton().getFieldValue("GroundObject", "floor", ref);
    }

    public int getHash() {
        return (int)AppletLoader.getSingleton().getFieldValue("GroundObject", "hash", ref);
    }

    public int getRenderInfoBitPacked() {
        return (int)AppletLoader.getSingleton().getFieldValue("GroundObject", "renderInfoBitPacked", ref);
    }

}
