/*
 * RSGrandExchangeOffer.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: a => java.lang.Object
public class RSGrandExchangeOffer extends RSClassWrapper {

    public RSGrandExchangeOffer(Object ref) {
        super(ref);
    }

    public int getItemId() {
        return (int)AppletLoader.getSingleton().getFieldValue("GrandExchangeOffer", "itemId", ref);
    }

    public int getTotalQuantity() {
        return (int)AppletLoader.getSingleton().getFieldValue("GrandExchangeOffer", "totalQuantity", ref);
    }

    public static RSJagexLoginType getJagexLoginType() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("GrandExchangeOffer", "jagexLoginType", null);
        RSJagexLoginType wrappers = null;
        if(objects != null)
            wrappers = (RSJagexLoginType)getWrapper(objects);
        return wrappers;
    }

    public int getPrice() {
        return (int)AppletLoader.getSingleton().getFieldValue("GrandExchangeOffer", "price", ref);
    }

    public int getSpent() {
        return (int)AppletLoader.getSingleton().getFieldValue("GrandExchangeOffer", "spent", ref);
    }

    public byte getProgress() {
        return (byte)AppletLoader.getSingleton().getFieldValue("GrandExchangeOffer", "progress", ref);
    }

    public int getQuantitySold() {
        return (int)AppletLoader.getSingleton().getFieldValue("GrandExchangeOffer", "quantitySold", ref);
    }

}
