/*
 * RSGrandExchangeEvents.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: w => java.lang.Object
public class RSGrandExchangeEvents extends RSClassWrapper {

    public RSGrandExchangeEvents(Object ref) {
        super(ref);
    }

    public java.util.List getEvents() {
        return (java.util.List)AppletLoader.getSingleton().getFieldValue("GrandExchangeEvents", "events", ref);
    }

}
