/*
 * RSGraphicsObject.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: cs => eo (Renderable) => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSGraphicsObject extends RSRenderable {

    public RSGraphicsObject(Object ref) {
        super(ref);
    }

    public int getLevel() {
        return (int)AppletLoader.getSingleton().getFieldValue("GraphicsObject", "level", ref);
    }

    public int getStartCycle() {
        return (int)AppletLoader.getSingleton().getFieldValue("GraphicsObject", "startCycle", ref);
    }

    public int getX() {
        return (int)AppletLoader.getSingleton().getFieldValue("GraphicsObject", "x", ref);
    }

    public int getY() {
        return (int)AppletLoader.getSingleton().getFieldValue("GraphicsObject", "y", ref);
    }

    public boolean getFinished() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("GraphicsObject", "finished", ref);
    }

    public int getId() {
        return (int)AppletLoader.getSingleton().getFieldValue("GraphicsObject", "id", ref);
    }

    public int getHeight() {
        return (int)AppletLoader.getSingleton().getFieldValue("GraphicsObject", "height", ref);
    }

}
