/*
 * RSGraphics3D.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: ef => kb (Rasterizer2D) => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSGraphics3D extends RSRasterizer2D {

    public RSGraphics3D(Object ref) {
        super(ref);
    }

    public static RSITextureLoader getTextureLoader() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Graphics3D", "textureLoader", null);
        RSITextureLoader wrappers = null;
        if(objects != null)
            wrappers = (RSITextureLoader)getWrapper(objects);
        return wrappers;
    }

    public static int getCenterY() {
        return (int)AppletLoader.getSingleton().getFieldValue("Graphics3D", "centerY", null);
    }

    public static int getRasterizer3D_clipHeight() {
        return (int)AppletLoader.getSingleton().getFieldValue("Graphics3D", "Rasterizer3D_clipHeight", null);
    }

    public static int getCenterX() {
        return (int)AppletLoader.getSingleton().getFieldValue("Graphics3D", "centerX", null);
    }

    public static int getRasterizer3D_clipMidX2() {
        return (int)AppletLoader.getSingleton().getFieldValue("Graphics3D", "Rasterizer3D_clipMidX2", null);
    }

    public static int getRasterizer3D_clipMidY2() {
        return (int)AppletLoader.getSingleton().getFieldValue("Graphics3D", "Rasterizer3D_clipMidY2", null);
    }

    public static int[] getSINE() {
        return (int[])AppletLoader.getSingleton().getFieldValue("Graphics3D", "SINE", null);
    }

    public static int[] getCOSINE() {
        return (int[])AppletLoader.getSingleton().getFieldValue("Graphics3D", "COSINE", null);
    }

    public static int getRasterizer3D_clipNegativeMidY() {
        return (int)AppletLoader.getSingleton().getFieldValue("Graphics3D", "Rasterizer3D_clipNegativeMidY", null);
    }

    public static int getRasterizer3D_clipNegativeMidX() {
        return (int)AppletLoader.getSingleton().getFieldValue("Graphics3D", "Rasterizer3D_clipNegativeMidX", null);
    }

    public static int getRasterAlpha() {
        return (int)AppletLoader.getSingleton().getFieldValue("Graphics3D", "rasterAlpha", null);
    }

    public static int getRasterClipX() {
        return (int)AppletLoader.getSingleton().getFieldValue("Graphics3D", "rasterClipX", null);
    }

    public static int[] getColorPalette() {
        return (int[])AppletLoader.getSingleton().getFieldValue("Graphics3D", "colorPalette", null);
    }

    public static boolean getRasterClipEnable() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("Graphics3D", "rasterClipEnable", null);
    }

    public static int[] getRasterClipY() {
        return (int[])AppletLoader.getSingleton().getFieldValue("Graphics3D", "rasterClipY", null);
    }

    public static boolean getRasterGouraudLowRes() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("Graphics3D", "rasterGouraudLowRes", null);
    }

    public static int getRasterizer3D_zoom() {
        return (int)AppletLoader.getSingleton().getFieldValue("Graphics3D", "Rasterizer3D_zoom", null);
    }

    public static boolean getLowMem() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("Graphics3D", "lowMem", null);
    }

}
