/*
 * RSHashTableIterator.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: hy => java.lang.Object
public class RSHashTableIterator extends RSClassWrapper {

    public RSHashTableIterator(Object ref) {
        super(ref);
    }

    public RSNode getHead() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("HashTableIterator", "head", ref);
        RSNode wrappers = null;
        if(objects != null)
            wrappers = (RSNode)getWrapper(objects);
        return wrappers;
    }

    public RSNode getTail() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("HashTableIterator", "tail", ref);
        RSNode wrappers = null;
        if(objects != null)
            wrappers = (RSNode)getWrapper(objects);
        return wrappers;
    }

    public int getIndex() {
        return (int)AppletLoader.getSingleton().getFieldValue("HashTableIterator", "index", ref);
    }

    public RSIterableHashTable getTable() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("HashTableIterator", "table", ref);
        RSIterableHashTable wrappers = null;
        if(objects != null)
            wrappers = (RSIterableHashTable)getWrapper(objects);
        return wrappers;
    }

}
