/*
 * RSIdentifiers.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: gx => java.lang.Object
public class RSIdentifiers extends RSClassWrapper {

    public RSIdentifiers(Object ref) {
        super(ref);
    }

    public int[] getTable() {
        return (int[])AppletLoader.getSingleton().getFieldValue("Identifiers", "table", ref);
    }

}
