/*
 * RSIgnore.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: bl => java.lang.Object
public class RSIgnore extends RSClassWrapper {

    public RSIgnore(Object ref) {
        super(ref);
    }

    public java.lang.String getPreviousName() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("Ignore", "previousName", ref);
    }

    public java.lang.String getName() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("Ignore", "name", ref);
    }

}
