/*
 * RSInvType.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: iz => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSInvType extends RSCacheableNode {

    public RSInvType(Object ref) {
        super(ref);
    }

    public int getSize() {
        return (int)AppletLoader.getSingleton().getFieldValue("InvType", "size", ref);
    }

    public static RSNodeCache getInventoryCache() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("InvType", "inventoryCache", null);
        RSNodeCache wrappers = null;
        if(objects != null)
            wrappers = (RSNodeCache)getWrapper(objects);
        return wrappers;
    }

}
