/*
 * RSIndexStoreActionHandler.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ij => java.lang.Object
public class RSIndexStoreActionHandler extends RSClassWrapper {

    public RSIndexStoreActionHandler(Object ref) {
        super(ref);
    }

    public static RSDeque getIndexStoreActionHandler_responseQueue() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("IndexStoreActionHandler", "IndexStoreActionHandler_responseQueue", null);
        RSDeque wrappers = null;
        if(objects != null)
            wrappers = (RSDeque)getWrapper(objects);
        return wrappers;
    }

    public static java.lang.Object getIndexStoreActionHandler_lock() {
        return (java.lang.Object)AppletLoader.getSingleton().getFieldValue("IndexStoreActionHandler", "IndexStoreActionHandler_lock", null);
    }

    public static java.lang.Thread getIndexStoreActionHandler_thread() {
        return (java.lang.Thread)AppletLoader.getSingleton().getFieldValue("IndexStoreActionHandler", "IndexStoreActionHandler_thread", null);
    }

    public static RSDeque getIndexStoreActionHandler_requestQueue() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("IndexStoreActionHandler", "IndexStoreActionHandler_requestQueue", null);
        RSDeque wrappers = null;
        if(objects != null)
            wrappers = (RSDeque)getWrapper(objects);
        return wrappers;
    }

}
