/*
 * RSIndexFile.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: fv => java.lang.Object
public class RSIndexFile extends RSClassWrapper {

    public RSIndexFile(Object ref) {
        super(ref);
    }

    public int getIndex() {
        return (int)AppletLoader.getSingleton().getFieldValue("IndexFile", "index", ref);
    }

    public RSCacheFile getIndexFile() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("IndexFile", "indexFile", ref);
        RSCacheFile wrappers = null;
        if(objects != null)
            wrappers = (RSCacheFile)getWrapper(objects);
        return wrappers;
    }

    public RSCacheFile getDataFile() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("IndexFile", "dataFile", ref);
        RSCacheFile wrappers = null;
        if(objects != null)
            wrappers = (RSCacheFile)getWrapper(objects);
        return wrappers;
    }

    public int getMaxSize() {
        return (int)AppletLoader.getSingleton().getFieldValue("IndexFile", "maxSize", ref);
    }

    public static byte[] getIndexStore_buffer() {
        return (byte[])AppletLoader.getSingleton().getFieldValue("IndexFile", "IndexStore_buffer", null);
    }

}
