/*
 * RSISAACCipher.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: gz => java.lang.Object
public class RSISAACCipher extends RSClassWrapper {

    public RSISAACCipher(Object ref) {
        super(ref);
    }

    public int[] getMm() {
        return (int[])AppletLoader.getSingleton().getFieldValue("ISAACCipher", "mm", ref);
    }

    public int getValuesRemaining() {
        return (int)AppletLoader.getSingleton().getFieldValue("ISAACCipher", "valuesRemaining", ref);
    }

    public int[] getRandResult() {
        return (int[])AppletLoader.getSingleton().getFieldValue("ISAACCipher", "randResult", ref);
    }

}
