/*
 * RSItemLayer.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: dr => java.lang.Object
public class RSItemLayer extends RSClassWrapper {

    public RSItemLayer(Object ref) {
        super(ref);
    }

    public RSRenderable getMiddle() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("ItemLayer", "middle", ref);
        RSRenderable wrappers = null;
        if(objects != null)
            wrappers = (RSRenderable)getWrapper(objects);
        return wrappers;
    }

    public RSRenderable getTop() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("ItemLayer", "top", ref);
        RSRenderable wrappers = null;
        if(objects != null)
            wrappers = (RSRenderable)getWrapper(objects);
        return wrappers;
    }

    public RSRenderable getBottom() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("ItemLayer", "bottom", ref);
        RSRenderable wrappers = null;
        if(objects != null)
            wrappers = (RSRenderable)getWrapper(objects);
        return wrappers;
    }

    public int getFlags() {
        return (int)AppletLoader.getSingleton().getFieldValue("ItemLayer", "flags", ref);
    }

    public int getX() {
        return (int)AppletLoader.getSingleton().getFieldValue("ItemLayer", "x", ref);
    }

    public int getY() {
        return (int)AppletLoader.getSingleton().getFieldValue("ItemLayer", "y", ref);
    }

    public static RSIndexedSprite[] getSlFlagSprites() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("ItemLayer", "slFlagSprites", null);
        RSIndexedSprite[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSIndexedSprite[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSIndexedSprite)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public static Object[] getRSRef_SlFlagSprites() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("ItemLayer", "slFlagSprites", null);
    }

    public int getHash() {
        return (int)AppletLoader.getSingleton().getFieldValue("ItemLayer", "hash", ref);
    }

    public int getHeight() {
        return (int)AppletLoader.getSingleton().getFieldValue("ItemLayer", "height", ref);
    }

}
