/*
 * RSItemContainer.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: bt => gw (Node) => java.lang.Object
public class RSItemContainer extends RSNode {

    public RSItemContainer(Object ref) {
        super(ref);
    }

    public static RSHashTable getItemContainers() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("ItemContainer", "itemContainers", null);
        RSHashTable wrappers = null;
        if(objects != null)
            wrappers = (RSHashTable)getWrapper(objects);
        return wrappers;
    }

    public int[] getItemIds() {
        return (int[])AppletLoader.getSingleton().getFieldValue("ItemContainer", "itemIds", ref);
    }

    public static RSIndexedSprite[] getTitlemuteSprite() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("ItemContainer", "titlemuteSprite", null);
        RSIndexedSprite[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSIndexedSprite[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSIndexedSprite)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public static Object[] getRSRef_TitlemuteSprite() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("ItemContainer", "titlemuteSprite", null);
    }

    public int[] getStackSizes() {
        return (int[])AppletLoader.getSingleton().getFieldValue("ItemContainer", "stackSizes", ref);
    }

}
