/*
 * RSItem.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: ct => eo (Renderable) => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSItem extends RSRenderable {

    public RSItem(Object ref) {
        super(ref);
    }

    public int getQuantity() {
        return (int)AppletLoader.getSingleton().getFieldValue("Item", "quantity", ref);
    }

    public int getId() {
        return (int)AppletLoader.getSingleton().getFieldValue("Item", "id", ref);
    }

}
