/*
 * RSJagexGame.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: id => java.lang.Object
public class RSJagexGame extends RSClassWrapper {

    public RSJagexGame(Object ref) {
        super(ref);
    }

    public java.lang.String getName() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("JagexGame", "name", ref);
    }

    public int getId() {
        return (int)AppletLoader.getSingleton().getFieldValue("JagexGame", "id", ref);
    }

}
