/*
 * RSJagexLoginType.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: kh => java.lang.Object
public class RSJagexLoginType extends RSClassWrapper {

    public RSJagexLoginType(Object ref) {
        super(ref);
    }

    public java.lang.String getIdentifier() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("JagexLoginType", "identifier", ref);
    }

}
