/*
 * RSMainBufferProvider.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: bj => kr (BufferProvider) => java.lang.Object
public class RSMainBufferProvider extends RSBufferProvider {

    public RSMainBufferProvider(Object ref) {
        super(ref);
    }

    public java.awt.Image getImage() {
        return (java.awt.Image)AppletLoader.getSingleton().getFieldValue("MainBufferProvider", "image", ref);
    }

    public java.awt.Component getComponent() {
        return (java.awt.Component)AppletLoader.getSingleton().getFieldValue("MainBufferProvider", "component", ref);
    }

}
