/*
 * RSMessageNode.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: bs => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSMessageNode extends RSCacheableNode {

    public RSMessageNode(Object ref) {
        super(ref);
    }

    public java.lang.String getSender() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("MessageNode", "sender", ref);
    }

    public static java.lang.String getSessionToken() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("MessageNode", "sessionToken", null);
    }

    public java.lang.String getName() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("MessageNode", "name", ref);
    }

    public int getTick() {
        return (int)AppletLoader.getSingleton().getFieldValue("MessageNode", "tick", ref);
    }

    public int getId() {
        return (int)AppletLoader.getSingleton().getFieldValue("MessageNode", "id", ref);
    }

    public int getType() {
        return (int)AppletLoader.getSingleton().getFieldValue("MessageNode", "type", ref);
    }

    public java.lang.String getValue() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("MessageNode", "value", ref);
    }

    public static RSSpritePixels[] getCrossSprites() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("MessageNode", "crossSprites", null);
        RSSpritePixels[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSSpritePixels[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSSpritePixels)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public static Object[] getRSRef_CrossSprites() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("MessageNode", "crossSprites", null);
    }

}
