/*
 * RSMilliTimer.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: ez => fm (Timer) => java.lang.Object
public class RSMilliTimer extends RSTimer {

    public RSMilliTimer(Object ref) {
        super(ref);
    }

    public long getMilliTime() {
        return (long)AppletLoader.getSingleton().getFieldValue("MilliTimer", "milliTime", ref);
    }

    public int getSleepTime() {
        return (int)AppletLoader.getSingleton().getFieldValue("MilliTimer", "sleepTime", ref);
    }

    public static short[] getColorsToFind() {
        return (short[])AppletLoader.getSingleton().getFieldValue("MilliTimer", "colorsToFind", null);
    }

}
