/*
 * RSMouseRecorder.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: bv => java.lang.Object
public class RSMouseRecorder extends RSClassWrapper {

    public RSMouseRecorder(Object ref) {
        super(ref);
    }

    public boolean getIsRunning() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("MouseRecorder", "isRunning", ref);
    }

    public int getIndex() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseRecorder", "index", ref);
    }

    public java.lang.Object getLock() {
        return (java.lang.Object)AppletLoader.getSingleton().getFieldValue("MouseRecorder", "lock", ref);
    }

    public int[] getYs() {
        return (int[])AppletLoader.getSingleton().getFieldValue("MouseRecorder", "ys", ref);
    }

    public int[] getXs() {
        return (int[])AppletLoader.getSingleton().getFieldValue("MouseRecorder", "xs", ref);
    }

}
