/*
 * RSMouseWheelHandler.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ai => java.lang.Object
public class RSMouseWheelHandler extends RSClassWrapper {

    public RSMouseWheelHandler(Object ref) {
        super(ref);
    }

    public int getRotation() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseWheelHandler", "rotation", ref);
    }

}
