/*
 * RSMouseInput.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: bi => java.lang.Object
public class RSMouseInput extends RSClassWrapper {

    public RSMouseInput(Object ref) {
        super(ref);
    }

    public static int getMouseLastX() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "mouseLastX", null);
    }

    public static int getMouseX() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "mouseX", null);
    }

    public static int getMouseHandler_lastPressedY() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "MouseHandler_lastPressedY", null);
    }

    public static int getMouseHandler_lastPressedX() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "MouseHandler_lastPressedX", null);
    }

    public static int getMouseLastY() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "mouseLastY", null);
    }

    public static long getMouseLastPressedTimeMillis() {
        return (long)AppletLoader.getSingleton().getFieldValue("MouseInput", "mouseLastPressedTimeMillis", null);
    }

    public static int getMouseCurrentButton() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "mouseCurrentButton", null);
    }

    public static RSIndexData getIndexCache10() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("MouseInput", "indexCache10", null);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

    public static int getMouseY() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "mouseY", null);
    }

    public static int getMouseHandler_currentButton() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "MouseHandler_currentButton", null);
    }

    public static int getMouseLastPressedY() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "mouseLastPressedY", null);
    }

    public static int getMouseHandler_lastButton() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "MouseHandler_lastButton", null);
    }

    public static int getMouseLastPressedX() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "mouseLastPressedX", null);
    }

    public static int getMouseLastButton() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "mouseLastButton", null);
    }

    public static RSMouseInput getMouse() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("MouseInput", "mouse", null);
        RSMouseInput wrappers = null;
        if(objects != null)
            wrappers = (RSMouseInput)getWrapper(objects);
        return wrappers;
    }

    public static int getMouseIdleTicks() {
        return (int)AppletLoader.getSingleton().getFieldValue("MouseInput", "mouseIdleTicks", null);
    }

    public static RSIndexData getIndexModels() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("MouseInput", "indexModels", null);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

    public static long getMouseHandler_lastPressedTimeMillis() {
        return (long)AppletLoader.getSingleton().getFieldValue("MouseInput", "MouseHandler_lastPressedTimeMillis", null);
    }

}
