/*
 * RSNanoTimer.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: em => fm (Timer) => java.lang.Object
public class RSNanoTimer extends RSTimer {

    public RSNanoTimer(Object ref) {
        super(ref);
    }

    public long getNanoTime() {
        return (long)AppletLoader.getSingleton().getFieldValue("NanoTimer", "nanoTime", ref);
    }

}
