/*
 * RSNetWriter.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: cg => java.lang.Object
public class RSNetWriter extends RSClassWrapper {

    public RSNetWriter(Object ref) {
        super(ref);
    }

    public RSPacketBuffer getPacketBuffer() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("NetWriter", "packetBuffer", ref);
        RSPacketBuffer wrappers = null;
        if(objects != null)
            wrappers = (RSPacketBuffer)getWrapper(objects);
        return wrappers;
    }

    public int getPacketLength() {
        return (int)AppletLoader.getSingleton().getFieldValue("NetWriter", "packetLength", ref);
    }

    public RSServerPacket getServerPacket() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("NetWriter", "serverPacket", ref);
        RSServerPacket wrappers = null;
        if(objects != null)
            wrappers = (RSServerPacket)getWrapper(objects);
        return wrappers;
    }

    public RSCombatInfoList getPacketBufferNodes() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("NetWriter", "packetBufferNodes", ref);
        RSCombatInfoList wrappers = null;
        if(objects != null)
            wrappers = (RSCombatInfoList)getWrapper(objects);
        return wrappers;
    }

    public RSBuffer getBuffer() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("NetWriter", "buffer", ref);
        RSBuffer wrappers = null;
        if(objects != null)
            wrappers = (RSBuffer)getWrapper(objects);
        return wrappers;
    }

    public RSClass159 getRssocket() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("NetWriter", "rssocket", ref);
        RSClass159 wrappers = null;
        if(objects != null)
            wrappers = (RSClass159)getWrapper(objects);
        return wrappers;
    }

}
