/*
 * RSNode.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: gw => java.lang.Object
public class RSNode extends RSClassWrapper {

    public RSNode(Object ref) {
        super(ref);
    }

    public RSNode getNext() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Node", "next", ref);
        RSNode wrappers = null;
        if(objects != null)
            wrappers = (RSNode)getWrapper(objects);
        return wrappers;
    }

    public RSNode getPrevious() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Node", "previous", ref);
        RSNode wrappers = null;
        if(objects != null)
            wrappers = (RSNode)getWrapper(objects);
        return wrappers;
    }

    public long getHash() {
        return (long)AppletLoader.getSingleton().getFieldValue("Node", "hash", ref);
    }

}
