/*
 * RSNode2LinkedList.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: gh => java.lang.Object
public class RSNode2LinkedList extends RSClassWrapper {

    public RSNode2LinkedList(Object ref) {
        super(ref);
    }

    public RSCacheableNode getSentinel() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Node2LinkedList", "sentinel", ref);
        RSCacheableNode wrappers = null;
        if(objects != null)
            wrappers = (RSCacheableNode)getWrapper(objects);
        return wrappers;
    }

}
