/*
 * RSNPC.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: cq => bm (Actor) => eo (Renderable) => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSNPC extends RSActor {

    public RSNPC(Object ref) {
        super(ref);
    }

    public RSNPCComposition getComposition() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("NPC", "composition", ref);
        RSNPCComposition wrappers = null;
        if(objects != null)
            wrappers = (RSNPCComposition)getWrapper(objects);
        return wrappers;
    }

}
