/*
 * RSObjectNode.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: gu => gw (Node) => java.lang.Object
public class RSObjectNode extends RSNode {

    public RSObjectNode(Object ref) {
        super(ref);
    }

    public java.lang.Object getValue() {
        return (java.lang.Object)AppletLoader.getSingleton().getFieldValue("ObjectNode", "value", ref);
    }

}
