/*
 * RSPacketNode.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: fy => gw (Node) => java.lang.Object
public class RSPacketNode extends RSNode {

    public RSPacketNode(Object ref) {
        super(ref);
    }

    public RSPacketBuffer getPacketBuffer() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("PacketNode", "packetBuffer", ref);
        RSPacketBuffer wrappers = null;
        if(objects != null)
            wrappers = (RSPacketBuffer)getWrapper(objects);
        return wrappers;
    }

    public RSClientPacket getClientPacket() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("PacketNode", "clientPacket", ref);
        RSClientPacket wrappers = null;
        if(objects != null)
            wrappers = (RSClientPacket)getWrapper(objects);
        return wrappers;
    }

    public static RSPacketNode[] getPacketBufferNodes() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("PacketNode", "packetBufferNodes", null);
        RSPacketNode[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSPacketNode[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSPacketNode)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public static Object[] getRSRef_PacketBufferNodes() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("PacketNode", "packetBufferNodes", null);
    }

}
