/*
 * RSParameters.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: kz => java.lang.Object
public class RSParameters extends RSClassWrapper {

    public RSParameters(Object ref) {
        super(ref);
    }

    public java.lang.String getKey() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("Parameters", "key", ref);
    }

}
