/*
 * RSPacketBuffer.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: gr => gv (Buffer) => gw (Node) => java.lang.Object
public class RSPacketBuffer extends RSBuffer {

    public RSPacketBuffer(Object ref) {
        super(ref);
    }

    public RSISAACCipher getCipher() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("PacketBuffer", "cipher", ref);
        RSISAACCipher wrappers = null;
        if(objects != null)
            wrappers = (RSISAACCipher)getWrapper(objects);
        return wrappers;
    }

    public int getBitPosition() {
        return (int)AppletLoader.getSingleton().getFieldValue("PacketBuffer", "bitPosition", ref);
    }

}
