/*
 * RSPendingSpawn.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: bc => gw (Node) => java.lang.Object
public class RSPendingSpawn extends RSNode {

    public RSPendingSpawn(Object ref) {
        super(ref);
    }

    public int getHitpoints() {
        return (int)AppletLoader.getSingleton().getFieldValue("PendingSpawn", "hitpoints", ref);
    }

    public int getOrientation() {
        return (int)AppletLoader.getSingleton().getFieldValue("PendingSpawn", "orientation", ref);
    }

    public int getDelay() {
        return (int)AppletLoader.getSingleton().getFieldValue("PendingSpawn", "delay", ref);
    }

    public int getLevel() {
        return (int)AppletLoader.getSingleton().getFieldValue("PendingSpawn", "level", ref);
    }

    public int getX() {
        return (int)AppletLoader.getSingleton().getFieldValue("PendingSpawn", "x", ref);
    }

    public int getY() {
        return (int)AppletLoader.getSingleton().getFieldValue("PendingSpawn", "y", ref);
    }

    public int getId() {
        return (int)AppletLoader.getSingleton().getFieldValue("PendingSpawn", "id", ref);
    }

    public int getType() {
        return (int)AppletLoader.getSingleton().getFieldValue("PendingSpawn", "type", ref);
    }

}
