/*
 * RSPreferences.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ck => java.lang.Object
public class RSPreferences extends RSClassWrapper {

    public RSPreferences(Object ref) {
        super(ref);
    }

    public java.util.LinkedHashMap getPreferences() {
        return (java.util.LinkedHashMap)AppletLoader.getSingleton().getFieldValue("Preferences", "preferences", ref);
    }

    public boolean getHideUsername() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("Preferences", "hideUsername", ref);
    }

    public boolean getHideRoofs() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("Preferences", "hideRoofs", ref);
    }

    public java.lang.String getRememberedUsername() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("Preferences", "rememberedUsername", ref);
    }

    public int getScreenType() {
        return (int)AppletLoader.getSingleton().getFieldValue("Preferences", "screenType", ref);
    }

    public boolean getMuted() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("Preferences", "muted", ref);
    }

}
