/*
 * RSResidue.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: dv => java.lang.Object
public class RSResidue extends RSClassWrapper {

    public RSResidue(Object ref) {
        super(ref);
    }

    public int getClassBook() {
        return (int)AppletLoader.getSingleton().getFieldValue("Residue", "classBook", ref);
    }

    public int getPartitionSize() {
        return (int)AppletLoader.getSingleton().getFieldValue("Residue", "partitionSize", ref);
    }

    public int getEnd() {
        return (int)AppletLoader.getSingleton().getFieldValue("Residue", "end", ref);
    }

    public int getType() {
        return (int)AppletLoader.getSingleton().getFieldValue("Residue", "type", ref);
    }

    public int getClassification() {
        return (int)AppletLoader.getSingleton().getFieldValue("Residue", "classification", ref);
    }

    public int getBegin() {
        return (int)AppletLoader.getSingleton().getFieldValue("Residue", "begin", ref);
    }

}
