/*
 * RSRenderable.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: eo => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSRenderable extends RSCacheableNode {

    public RSRenderable(Object ref) {
        super(ref);
    }

    public static RSIndexData getIndexSprites() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Renderable", "indexSprites", null);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

    public int getModelHeight() {
        return (int)AppletLoader.getSingleton().getFieldValue("Renderable", "modelHeight", ref);
    }

    public static RSAbstractSoundSystem getSoundSystem0() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Renderable", "soundSystem0", null);
        RSAbstractSoundSystem wrappers = null;
        if(objects != null)
            wrappers = (RSAbstractSoundSystem)getWrapper(objects);
        return wrappers;
    }

}
