/*
 * RSRunException.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ey => java.lang.RuntimeException
public class RSRunException extends RSClassWrapper {

    public RSRunException(Object ref) {
        super(ref);
    }

    public static java.lang.String getLocalPlayerName() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("RunException", "localPlayerName", null);
    }

    public static RSIndexData getIndexTrack2() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("RunException", "indexTrack2", null);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

}
