/*
 * RSScriptVarType.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: s => java.lang.Object
public class RSScriptVarType extends RSClassWrapper {

    public RSScriptVarType(Object ref) {
        super(ref);
    }

    public char getTypeChar() {
        return (char)AppletLoader.getSingleton().getFieldValue("ScriptVarType", "typeChar", ref);
    }

    public int getId() {
        return (int)AppletLoader.getSingleton().getFieldValue("ScriptVarType", "id", ref);
    }

}
