/*
 * RSServerPacket.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: fn => java.lang.Object
public class RSServerPacket extends RSClassWrapper {

    public RSServerPacket(Object ref) {
        super(ref);
    }

    public int getPacketId() {
        return (int)AppletLoader.getSingleton().getFieldValue("ServerPacket", "packetId", ref);
    }

    public int getPacketLength() {
        return (int)AppletLoader.getSingleton().getFieldValue("ServerPacket", "packetLength", ref);
    }

}
