/*
 * RSSize.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: k => java.lang.Object
public class RSSize extends RSClassWrapper {

    public RSSize(Object ref) {
        super(ref);
    }

    public static RSIndexData getIndexTrack1() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Size", "indexTrack1", null);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

}
