/*
 * RSSignlink.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ff => java.lang.Object
public class RSSignlink extends RSClassWrapper {

    public RSSignlink(Object ref) {
        super(ref);
    }

    public static RSTimer getTimer() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Signlink", "timer", null);
        RSTimer wrappers = null;
        if(objects != null)
            wrappers = (RSTimer)getWrapper(objects);
        return wrappers;
    }

    public RSTask getCachedTask() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Signlink", "cachedTask", ref);
        RSTask wrappers = null;
        if(objects != null)
            wrappers = (RSTask)getWrapper(objects);
        return wrappers;
    }

    public static java.lang.String getJavaVersion() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("Signlink", "javaVersion", null);
    }

    public RSTask getCurrentTask() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Signlink", "currentTask", ref);
        RSTask wrappers = null;
        if(objects != null)
            wrappers = (RSTask)getWrapper(objects);
        return wrappers;
    }

    public boolean getClosed() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("Signlink", "closed", ref);
    }

    public static java.lang.String getJavaVendor() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("Signlink", "javaVendor", null);
    }

    public java.lang.Thread getSysEventQueue() {
        return (java.lang.Thread)AppletLoader.getSingleton().getFieldValue("Signlink", "sysEventQueue", ref);
    }

    public static RSUrlRequester getUrlRequester() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Signlink", "urlRequester", null);
        RSUrlRequester wrappers = null;
        if(objects != null)
            wrappers = (RSUrlRequester)getWrapper(objects);
        return wrappers;
    }

}
