/*
 * RSSoundTask.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: db => java.lang.Object
public class RSSoundTask extends RSClassWrapper {

    public RSSoundTask(Object ref) {
        super(ref);
    }

    public RSAbstractSoundSystem[] getSystems() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("SoundTask", "systems", ref);
        RSAbstractSoundSystem[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSAbstractSoundSystem[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSAbstractSoundSystem)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public Object[] getRSRef_Systems() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("SoundTask", "systems", ref);
    }

    public static java.lang.String getOsName() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("SoundTask", "osName", null);
    }

}
