/*
 * RSSourceDataSoundSystem.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: by => dd (AbstractSoundSystem) => java.lang.Object
public class RSSourceDataSoundSystem extends RSAbstractSoundSystem {

    public RSSourceDataSoundSystem(Object ref) {
        super(ref);
    }

    public int getSize() {
        return (int)AppletLoader.getSingleton().getFieldValue("SourceDataSoundSystem", "size", ref);
    }

    public byte[] getBytes() {
        return (byte[])AppletLoader.getSingleton().getFieldValue("SourceDataSoundSystem", "bytes", ref);
    }

    public javax.sound.sampled.AudioFormat getAudioFormat() {
        return (javax.sound.sampled.AudioFormat)AppletLoader.getSingleton().getFieldValue("SourceDataSoundSystem", "audioFormat", ref);
    }

    public javax.sound.sampled.SourceDataLine getSource() {
        return (javax.sound.sampled.SourceDataLine)AppletLoader.getSingleton().getFieldValue("SourceDataSoundSystem", "source", ref);
    }

}
