/*
 * RSSoundEffect.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: dq => java.lang.Object
public class RSSoundEffect extends RSClassWrapper {

    public RSSoundEffect(Object ref) {
        super(ref);
    }

    public RSAudioInstrument[] getInstruments() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("SoundEffect", "instruments", ref);
        RSAudioInstrument[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSAudioInstrument[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSAudioInstrument)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public Object[] getRSRef_Instruments() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("SoundEffect", "instruments", ref);
    }

    public int getStart() {
        return (int)AppletLoader.getSingleton().getFieldValue("SoundEffect", "start", ref);
    }

    public int getEnd() {
        return (int)AppletLoader.getSingleton().getFieldValue("SoundEffect", "end", ref);
    }

}
