/*
 * RSSpotanim.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: iy => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSSpotanim extends RSCacheableNode {

    public RSSpotanim(Object ref) {
        super(ref);
    }

    public static RSNodeCache getSpotanims() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Spotanim", "spotanims", null);
        RSNodeCache wrappers = null;
        if(objects != null)
            wrappers = (RSNodeCache)getWrapper(objects);
        return wrappers;
    }

    public int getWidthScale() {
        return (int)AppletLoader.getSingleton().getFieldValue("Spotanim", "widthScale", ref);
    }

    public static RSNodeCache getSpotAnimationDefinition_cachedModels() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Spotanim", "SpotAnimationDefinition_cachedModels", null);
        RSNodeCache wrappers = null;
        if(objects != null)
            wrappers = (RSNodeCache)getWrapper(objects);
        return wrappers;
    }

    public int getOrientation() {
        return (int)AppletLoader.getSingleton().getFieldValue("Spotanim", "orientation", ref);
    }

    public static RSIndexDataBase getSpotAnimationDefinition_indexCache() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Spotanim", "SpotAnimationDefinition_indexCache", null);
        RSIndexDataBase wrappers = null;
        if(objects != null)
            wrappers = (RSIndexDataBase)getWrapper(objects);
        return wrappers;
    }

    public int getHeightScale() {
        return (int)AppletLoader.getSingleton().getFieldValue("Spotanim", "heightScale", ref);
    }

    public static RSIndexDataBase getSpotAnimationDefinition_modelIndexCache() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Spotanim", "SpotAnimationDefinition_modelIndexCache", null);
        RSIndexDataBase wrappers = null;
        if(objects != null)
            wrappers = (RSIndexDataBase)getWrapper(objects);
        return wrappers;
    }

    public int getId() {
        return (int)AppletLoader.getSingleton().getFieldValue("Spotanim", "id", ref);
    }

}
