/*
 * RSSpritePixels.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: kg => kb (Rasterizer2D) => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSSpritePixels extends RSRasterizer2D {

    public RSSpritePixels(Object ref) {
        super(ref);
    }

    public int getOffsetX() {
        return (int)AppletLoader.getSingleton().getFieldValue("SpritePixels", "offsetX", ref);
    }

    public int[] getPixels() {
        return (int[])AppletLoader.getSingleton().getFieldValue("SpritePixels", "pixels", ref);
    }

    public int getOffsetY() {
        return (int)AppletLoader.getSingleton().getFieldValue("SpritePixels", "offsetY", ref);
    }

    public int getMaxHeight() {
        return (int)AppletLoader.getSingleton().getFieldValue("SpritePixels", "maxHeight", ref);
    }

    public int getWidth() {
        return (int)AppletLoader.getSingleton().getFieldValue("SpritePixels", "width", ref);
    }

    public int getHeight() {
        return (int)AppletLoader.getSingleton().getFieldValue("SpritePixels", "height", ref);
    }

    public int getMaxWidth() {
        return (int)AppletLoader.getSingleton().getFieldValue("SpritePixels", "maxWidth", ref);
    }

}
