/*
 * RSTask.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: et => java.lang.Object
public class RSTask extends RSClassWrapper {

    public RSTask(Object ref) {
        super(ref);
    }

    public java.lang.Object getObjectArgument() {
        return (java.lang.Object)AppletLoader.getSingleton().getFieldValue("Task", "objectArgument", ref);
    }

    public RSTask getTask() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Task", "task", ref);
        RSTask wrappers = null;
        if(objects != null)
            wrappers = (RSTask)getWrapper(objects);
        return wrappers;
    }

    public int getIntArgument() {
        return (int)AppletLoader.getSingleton().getFieldValue("Task", "intArgument", ref);
    }

    public int getType() {
        return (int)AppletLoader.getSingleton().getFieldValue("Task", "type", ref);
    }

    public java.lang.Object getValue() {
        return (java.lang.Object)AppletLoader.getSingleton().getFieldValue("Task", "value", ref);
    }

    public int getStatus() {
        return (int)AppletLoader.getSingleton().getFieldValue("Task", "status", ref);
    }

}
