/*
 * RSTimer.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: fm => java.lang.Object
public class RSTimer extends RSClassWrapper {

    public RSTimer(Object ref) {
        super(ref);
    }

    public static RSIndexData getIndexScripts() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("Timer", "indexScripts", null);
        RSIndexData wrappers = null;
        if(objects != null)
            wrappers = (RSIndexData)getWrapper(objects);
        return wrappers;
    }

}
