/*
 * RSUrlRequester.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: el => java.lang.Object
public class RSUrlRequester extends RSClassWrapper {

    public RSUrlRequester(Object ref) {
        super(ref);
    }

    public boolean getIsClosed() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("UrlRequester", "isClosed", ref);
    }

    public java.lang.Thread getThread() {
        return (java.lang.Thread)AppletLoader.getSingleton().getFieldValue("UrlRequester", "thread", ref);
    }

    public java.util.Queue getRequests() {
        return (java.util.Queue)AppletLoader.getSingleton().getFieldValue("UrlRequester", "requests", ref);
    }

    public static RSAbstractSoundSystem getSoundSystem1() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("UrlRequester", "soundSystem1", null);
        RSAbstractSoundSystem wrappers = null;
        if(objects != null)
            wrappers = (RSAbstractSoundSystem)getWrapper(objects);
        return wrappers;
    }

}
