/*
 * RSVarcs.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: cn => java.lang.Object
public class RSVarcs extends RSClassWrapper {

    public RSVarcs(Object ref) {
        super(ref);
    }

    public boolean[] getVarcSerials() {
        return (boolean[])AppletLoader.getSingleton().getFieldValue("Varcs", "varcSerials", ref);
    }

    public java.lang.String[] getVarcstrings() {
        return (java.lang.String[])AppletLoader.getSingleton().getFieldValue("Varcs", "varcstrings", ref);
    }

    public boolean[] getVarcstringSerials() {
        return (boolean[])AppletLoader.getSingleton().getFieldValue("Varcs", "varcstringSerials", ref);
    }

    public long getLastSerialize() {
        return (long)AppletLoader.getSingleton().getFieldValue("Varcs", "lastSerialize", ref);
    }

    public int[] getVarcs() {
        return (int[])AppletLoader.getSingleton().getFieldValue("Varcs", "varcs", ref);
    }

    public boolean getChanged() {
        return (boolean)AppletLoader.getSingleton().getFieldValue("Varcs", "changed", ref);
    }

}
