/*
 * RSVarPlayerType.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: im => gd (CacheableNode) => gw (Node) => java.lang.Object
public class RSVarPlayerType extends RSCacheableNode {

    public RSVarPlayerType(Object ref) {
        super(ref);
    }

    public static RSSpritePixels getCompass() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("VarPlayerType", "compass", null);
        RSSpritePixels wrappers = null;
        if(objects != null)
            wrappers = (RSSpritePixels)getWrapper(objects);
        return wrappers;
    }

    public static RSNodeCache getVarplayers() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("VarPlayerType", "varplayers", null);
        RSNodeCache wrappers = null;
        if(objects != null)
            wrappers = (RSNodeCache)getWrapper(objects);
        return wrappers;
    }

    public int getConfigType() {
        return (int)AppletLoader.getSingleton().getFieldValue("VarPlayerType", "configType", ref);
    }

}
