/*
 * RSWallObject.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: er => java.lang.Object
public class RSWallObject extends RSClassWrapper {

    public RSWallObject(Object ref) {
        super(ref);
    }

    public RSRenderable getRenderable1() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("WallObject", "renderable1", ref);
        RSRenderable wrappers = null;
        if(objects != null)
            wrappers = (RSRenderable)getWrapper(objects);
        return wrappers;
    }

    public RSRenderable getRenderable2() {
        Object objects = (Object)AppletLoader.getSingleton().getFieldValue("WallObject", "renderable2", ref);
        RSRenderable wrappers = null;
        if(objects != null)
            wrappers = (RSRenderable)getWrapper(objects);
        return wrappers;
    }

    public int getX() {
        return (int)AppletLoader.getSingleton().getFieldValue("WallObject", "x", ref);
    }

    public int getY() {
        return (int)AppletLoader.getSingleton().getFieldValue("WallObject", "y", ref);
    }

    public int getOrientationB() {
        return (int)AppletLoader.getSingleton().getFieldValue("WallObject", "orientationB", ref);
    }

    public int getOrientationA() {
        return (int)AppletLoader.getSingleton().getFieldValue("WallObject", "orientationA", ref);
    }

    public int getFloor() {
        return (int)AppletLoader.getSingleton().getFieldValue("WallObject", "floor", ref);
    }

    public int getConfig() {
        return (int)AppletLoader.getSingleton().getFieldValue("WallObject", "config", ref);
    }

    public int getHash() {
        return (int)AppletLoader.getSingleton().getFieldValue("WallObject", "hash", ref);
    }

}
