/*
 * RSWidgetNode.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;

// Original name: bp => gw (Node) => java.lang.Object
public class RSWidgetNode extends RSNode {

    public RSWidgetNode(Object ref) {
        super(ref);
    }

    public int getOwner() {
        return (int)AppletLoader.getSingleton().getFieldValue("WidgetNode", "owner", ref);
    }

    public int getId() {
        return (int)AppletLoader.getSingleton().getFieldValue("WidgetNode", "id", ref);
    }

}
