/*
 * RSWorldMapData.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: az => java.lang.Object
public class RSWorldMapData extends RSClassWrapper {

    public RSWorldMapData(Object ref) {
        super(ref);
    }

    public static RSIndexedSprite[] getSlArrowSprites() {
        Object[] objects = (Object[])AppletLoader.getSingleton().getFieldValue("WorldMapData", "slArrowSprites", null);
        RSIndexedSprite[] wrappers = null;
        if(objects == null)
            return null;
        wrappers = new RSIndexedSprite[objects.length];
        for(int i = 0;i < objects.length;i++) {
            if(objects[i] != null)
                wrappers[i] = (RSIndexedSprite)getWrapper(objects[i]);
        }
        return wrappers;
    }

    public static Object[] getRSRef_SlArrowSprites() {
        return (Object[])AppletLoader.getSingleton().getFieldValue("WorldMapData", "slArrowSprites", null);
    }

    public int getFileId() {
        return (int)AppletLoader.getSingleton().getFieldValue("WorldMapData", "fileId", ref);
    }

}
