/*
 * RSWorldMapType2.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ab => java.lang.Object
public class RSWorldMapType2 extends RSClassWrapper {

    public RSWorldMapType2(Object ref) {
        super(ref);
    }

}
