/*
 * RSWorldMapType3.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ac => java.lang.Object
public class RSWorldMapType3 extends RSClassWrapper {

    public RSWorldMapType3(Object ref) {
        super(ref);
    }

    public static byte getClanChatRank() {
        return (byte)AppletLoader.getSingleton().getFieldValue("WorldMapType3", "clanChatRank", null);
    }

    public static int[][] getXteaKeys() {
        return (int[][])AppletLoader.getSingleton().getFieldValue("WorldMapType3", "xteaKeys", null);
    }

}
