/*
 * RSWorld.java
 * ---------------------------------------------------------------------------
 * Note: this file was automatically generated by the DankScape API Generator,
 * modifications to this file are useless as it will have to be regenerated often in the future.
 */

package dankscape.api.rs;

import dankscape.loader.AppletLoader;
import dankscape.api.internal.RSClassWrapper;

// Original name: ch => java.lang.Object
public class RSWorld extends RSClassWrapper {

    public RSWorld(Object ref) {
        super(ref);
    }

    public java.lang.String getAddress() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("World", "address", ref);
    }

    public java.lang.String getActivity() {
        return (java.lang.String)AppletLoader.getSingleton().getFieldValue("World", "activity", ref);
    }

    public int getPlayerCount() {
        return (int)AppletLoader.getSingleton().getFieldValue("World", "playerCount", ref);
    }

    public int getIndex() {
        return (int)AppletLoader.getSingleton().getFieldValue("World", "index", ref);
    }

    public int getLocation() {
        return (int)AppletLoader.getSingleton().getFieldValue("World", "location", ref);
    }

    public int getId() {
        return (int)AppletLoader.getSingleton().getFieldValue("World", "id", ref);
    }

    public int getMask() {
        return (int)AppletLoader.getSingleton().getFieldValue("World", "mask", ref);
    }

}
